#### Verificando e tratando dados sobre acidentes em BH

In [32]:
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

In [33]:
base_full = pd.read_excel('/home/luiz/Documentos/acidentes_bh/data/dados_carga_pbh.xlsx', sheet_name=None)

In [34]:
base_file  = pd.ExcelFile('/home/luiz/Documentos/acidentes_bh/data/dados_carga_pbh.xlsx')
print(base_file.sheet_names)

['boletins', 'envolvidos', 'veiculos', 'logradouros', 'coordenadas']

#### Separando DF por Planilha

In [35]:
dfs_limpos = {}

for nome_aba, df in base_full.items():
    temp_df = df.copy()

    temp_df.columns = [col.lower().strip() for col in temp_df.columns]

    dfs_limpos[nome_aba] = temp_df

#### Verificando os dados, se há nulos, como estão os tipos, para poder realizar o tratamento devido

In [36]:
dfs_limpos['boletins'].head(5)

,numero_boletim,tipo_acidente,desc_tipo_acidente,cod_tempo,desc_tempo,cod_pavimento,pavimento,cod_regional,desc_regional,origem_boletim,...,indicador_fatalidade,valor_ups,descricao_ups,data,hora,faixa_hora,faixa_hora_num,mês,ano,dia
0,2019026821139001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,25,PAMPULHA,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-06-07,13:38:00,Tarde,2,6,2019,7
1,2019027020851001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,19,CENTRO-SUL,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-06-08,17:07:00,Tarde,2,6,2019,8
2,2019032452512001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,25,PAMPULHA,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-07-08,16:21:00,Tarde,2,7,2019,8
3,2019032675416001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,22,NOROESTE,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-07-09,17:55:00,Tarde,2,7,2019,9
4,2019017864209001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,22,NOROESTE,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-04-17,14:08:00,Tarde,2,4,2019,17

In [ ]:
dfs_limpos['boletins'].drop(columns=['cod_boletins'], inplace=True)

In [37]:
dfs_limpos['boletins'].info()

<class 'pandas.DataFrame'>
RangeIndex: 71464 entries, 0 to 71463
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   numero_boletim        71464 non-null  str
 1   tipo_acidente         71464 non-null  str
 2   desc_tipo_acidente    71464 non-null  str
 3   cod_tempo             71464 non-null  int64
 4   desc_tempo            71464 non-null  str
 5   cod_pavimento         71464 non-null  int64
 6   pavimento             71464 non-null  str
 7   cod_regional          71464 non-null  int64
 8   desc_regional         69415 non-null  str
 9   origem_boletim        71464 non-null  str
 10  velocidade_permitida  71464 non-null  int64
 11  indicador_fatalidade  71464 non-null  str
 12  valor_ups             71464 non-null  int64
 13  descricao_ups         71464 non-null  str
 14  data                  71464 non-null  datetime64[us]
 15  hora                  71464 non-null  object
 16  faixa_hora            71464 non-null  str
 17  faixa_hora_num        71464 non-null  int64
 18  mês                   71464 non-null  int64
 19  ano                   71464 non-null  int64
 20  dia                   71464 non-null  int64
dtypes: datetime64[us](1), int64(9), object(1), str(10)
memory usage: 20.2+ MB

In [38]:
# Tratando o tipo da hora
dfs_limpos['boletins']['hora'] = pd.to_datetime(dfs_limpos['boletins']['hora'], format='%H:%M:%S', errors='coerce').dt.time

In [44]:
# Verificando a existencia de dados nulos
dfs_limpos['boletins'].isnull().sum()

cod_boletim             0
tipo_acidente           0
desc_tipo_acidente      0
cod_tempo               0
desc_tempo              0
cod_pavimento           0
pavimento               0
cod_regional            0
desc_regional           0
origem_boletim          0
velocidade_permitida    0
indicador_fatalidade    0
valor_ups               0
descricao_ups           0
data                    0
hora                    0
faixa_hora              0
faixa_hora_num          0
mês                     0
ano                     0
dia                     0
dtype: int64

In [40]:
# Tratando a desc_regional colocando como 'NAO_INFORMADO'
dfs_limpos['boletins']['desc_regional'] = dfs_limpos['boletins']['desc_regional'].fillna('NAO INFORMADO')

In [42]:
dfs_limpos['boletins'].duplicated().sum()

np.int64(0)

In [43]:
dfs_limpos['boletins'] = dfs_limpos['boletins'].rename(columns={'numero_boletim' : 'cod_boletim'})
dfs_limpos['boletins'].head(5)

,cod_boletim,tipo_acidente,desc_tipo_acidente,cod_tempo,desc_tempo,cod_pavimento,pavimento,cod_regional,desc_regional,origem_boletim,...,indicador_fatalidade,valor_ups,descricao_ups,data,hora,faixa_hora,faixa_hora_num,mês,ano,dia
0,2019026821139001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,25,PAMPULHA,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-06-07,13:38:00,Tarde,2,6,2019,7
1,2019027020851001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,19,CENTRO-SUL,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-06-08,17:07:00,Tarde,2,6,2019,8
2,2019032452512001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,25,PAMPULHA,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-07-08,16:21:00,Tarde,2,7,2019,8
3,2019032675416001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,22,NOROESTE,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-07-09,17:55:00,Tarde,2,7,2019,9
4,2019017864209001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,22,NOROESTE,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-04-17,14:08:00,Tarde,2,4,2019,17

In [45]:
dfs_limpos['envolvidos'].head(5)

,num_boletim,numero_envolvido,condutor,codigo_severidade,desc_severidade,sexo,cinto_seguranca,embreagues,idade,categoria_habilitacao,descricao_habilitacao,especie_veiculo,pedestre,passageiro,data,hora
0,2017004467915001,1,S,3,SEM FERIMENTOS,M,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,N,N,2017-02-28,21:13:00
1,2017029493511001,1,S,3,SEM FERIMENTOS,M,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,N,N,2017-10-10,13:31:00
2,2017027452746001,1,S,3,SEM FERIMENTOS,M,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,N,N,2017-09-27,07:36:00
3,2017030345024001,1,S,3,SEM FERIMENTOS,M,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,N,N,2017-10-16,09:39:00
4,2017030388086001,1,S,3,SEM FERIMENTOS,M,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,N,N,2017-10-16,14:52:00

In [48]:
dfs_limpos['envolvidos'].info()

<class 'pandas.DataFrame'>
RangeIndex: 154713 entries, 0 to 154712
Data columns (total 16 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   cod_boletim            154713 non-null  str
 1   numero_envolvido       154713 non-null  int64
 2   condutor               154713 non-null  object
 3   codigo_severidade      154713 non-null  int64
 4   desc_severidade        154713 non-null  str
 5   sexo                   154713 non-null  object
 6   cinto_seguranca        154713 non-null  str
 7   embreagues             154713 non-null  str
 8   idade                  154711 non-null  float64
 9   categoria_habilitacao  107199 non-null  str
 10  descricao_habilitacao  108198 non-null  str
 11  especie_veiculo        143297 non-null  str
 12  pedestre               147220 non-null  str
 13  passageiro             147608 non-null  str
 14  data                   154713 non-null  datetime64[us]
 15  hora                   154713 non-null  object
dtypes: datetime64[us](1), float64(1), int64(2), object(3), str(9)
memory usage: 32.0+ MB

In [47]:
dfs_limpos['envolvidos'] = dfs_limpos['envolvidos'].rename(columns={'num_boletim' : 'cod_boletim'})
dfs_limpos['envolvidos'].head(5)

,cod_boletim,numero_envolvido,condutor,codigo_severidade,desc_severidade,sexo,cinto_seguranca,embreagues,idade,categoria_habilitacao,descricao_habilitacao,especie_veiculo,pedestre,passageiro,data,hora
0,2017004467915001,1,S,3,SEM FERIMENTOS,M,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,N,N,2017-02-28,21:13:00
1,2017029493511001,1,S,3,SEM FERIMENTOS,M,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,N,N,2017-10-10,13:31:00
2,2017027452746001,1,S,3,SEM FERIMENTOS,M,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,N,N,2017-09-27,07:36:00
3,2017030345024001,1,S,3,SEM FERIMENTOS,M,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,N,N,2017-10-16,09:39:00
4,2017030388086001,1,S,3,SEM FERIMENTOS,M,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,N,N,2017-10-16,14:52:00

In [73]:
dfs_limpos['envolvidos']['idade'] = dfs_limpos['envolvidos']['idade'].astype('Int64')

In [75]:
dfs_limpos['envolvidos']['idade'].value_counts().sort_index()

idade
0      11168
1         75
2        104
3        123
4        127
       ...
99         1
100        1
105        1
117       14
121        2
Name: count, Length: 104, dtype: Int64

In [79]:
import numpy as np

# 1. Calculamos a MEDIANA apenas das idades que fazem sentido (ex: entre 1 e 98)
filtro_idades_reais = dfs_limpos['envolvidos']['idade'].between(1, 98)
mediana_idade = dfs_limpos['envolvidos']['idade'][filtro_idades_reais].median()

print(f"A mediana real calculada foi: {mediana_idade}")

# 2. Criamos uma função de limpeza
def limpar_idade(idade):
    # Se for 0 ou maior que 98, usamos a mediana
    if idade == 0 or idade > 98 or pd.isna(idade):
        return int(mediana_idade)
    return int(idade)

# 3. Aplicamos a limpeza
dfs_limpos['envolvidos']['idade'] = dfs_limpos['envolvidos']['idade'].apply(limpar_idade)

# 4. Agora convertemos para o int64 (minúsculo) - O Parquet vai amar isso!
dfs_limpos['envolvidos']['idade'] = dfs_limpos['envolvidos']['idade'].astype('int64')

# Conferindo o resultado
print(dfs_limpos['envolvidos']['idade'].value_counts().sort_index())

A mediana real calculada foi: 34.0
idade
1      75
2     104
3     123
4     127
5     137
     ...
94      3
95      5
96      2
97      4
98      1
Name: count, Length: 98, dtype: int64

In [77]:
# Trocando N por NÃO e S por SIM
dfs_limpos['envolvidos']['pedestre'] = dfs_limpos['envolvidos']['pedestre'].replace({'N': 'NÃO', 'S': 'SIM'})
dfs_limpos['envolvidos']['passageiro'] = dfs_limpos['envolvidos']['passageiro'].replace({'N': 'NÃO', 'S': 'SIM'})
dfs_limpos['envolvidos']['condutor'] = dfs_limpos['envolvidos']['condutor'].replace({'N': 'NÃO', 'S': 'SIM'})

In [80]:
colunas_cnh = ['categoria_habilitacao', 'descricao_habilitacao', 'especie_veiculo']

for col in colunas_cnh:
    dfs_limpos['envolvidos'][col] = dfs_limpos['envolvidos'][col].fillna('NAO SE APLICA')

In [81]:
dfs_limpos['envolvidos'].isnull().sum()

cod_boletim              0
numero_envolvido         0
condutor                 0
codigo_severidade        0
desc_severidade          0
sexo                     0
cinto_seguranca          0
embreagues               0
idade                    0
categoria_habilitacao    0
descricao_habilitacao    0
especie_veiculo          0
pedestre                 0
passageiro               0
dtype: int64

In [26]:
conflito = dfs_limpos['envolvidos'][(dfs_limpos['envolvidos']['pedestre'] == 'SIM') & (dfs_limpos['envolvidos']['passageiro'] == 'SIM')]
print(f"Quantidade de linhas com erro de lógica: {len(conflito)}")

Quantidade de linhas com erro de lógica: 0

In [53]:
col_pp = ['pedestre', 'passageiro']

for col in col_pp:
    dfs_limpos['envolvidos'][col] = dfs_limpos['envolvidos'][col].fillna('NAO INFORMADO')

In [55]:
tabelas_secundarias = ['envolvidos', 'veiculos', 'logradouros']

for nome in tabelas_secundarias:
    dfs_limpos[nome] = dfs_limpos[nome].drop(columns=['data', 'hora'], errors= 'ignore')

In [57]:
dfs_limpos['veiculos'] = dfs_limpos['veiculos'].rename(columns={'nº_boletim' : 'cod_boletim'})
dfs_limpos['logradouros'] = dfs_limpos['logradouros'].rename(columns={'nº_boletim' : 'cod_boletim'})

In [60]:
dfs_limpos['envolvidos']['sexo'].value_counts()

sexo
Masculino        112551
Feminino          36368
NAO INFORMADO      5794
Name: count, dtype: int64

In [59]:
map_sexo = {
    'M' : 'Masculino',
    'F' : 'Feminino',
    'NI': 'NAO INFORMADO',
    '0' : 'NAO INFORMADO',
    0 : 'NAO INFORMADO'
}

dfs_limpos['envolvidos']['sexo'] = dfs_limpos['envolvidos']['sexo'].replace(map_sexo)

In [61]:
dfs_limpos['boletins'].head(5)

,cod_boletim,tipo_acidente,desc_tipo_acidente,cod_tempo,desc_tempo,cod_pavimento,pavimento,cod_regional,desc_regional,origem_boletim,...,indicador_fatalidade,valor_ups,descricao_ups,data,hora,faixa_hora,faixa_hora_num,mês,ano,dia
0,2019026821139001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,25,PAMPULHA,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-06-07,13:38:00,Tarde,2,6,2019,7
1,2019027020851001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,19,CENTRO-SUL,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-06-08,17:07:00,Tarde,2,6,2019,8
2,2019032452512001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,25,PAMPULHA,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-07-08,16:21:00,Tarde,2,7,2019,8
3,2019032675416001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,22,NOROESTE,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-07-09,17:55:00,Tarde,2,7,2019,9
4,2019017864209001,H01002,ABALROAMENTO COM VITIMA,0,NAO INFORMADO,0,NAO INFORMADO,22,NOROESTE,POLICIA MILITAR,...,NÃO,0,NÃO INFORMADO,2019-04-17,14:08:00,Tarde,2,4,2019,17

In [62]:
dfs_limpos['envolvidos'].head(5)

,cod_boletim,numero_envolvido,condutor,codigo_severidade,desc_severidade,sexo,cinto_seguranca,embreagues,idade,categoria_habilitacao,descricao_habilitacao,especie_veiculo,pedestre,passageiro
0,2017004467915001,1,SIM,3,SEM FERIMENTOS,Masculino,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,NÃO,NÃO
1,2017029493511001,1,SIM,3,SEM FERIMENTOS,Masculino,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,NÃO,NÃO
2,2017027452746001,1,SIM,3,SEM FERIMENTOS,Masculino,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,NÃO,NÃO
3,2017030345024001,1,SIM,3,SEM FERIMENTOS,Masculino,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,NÃO,NÃO
4,2017030388086001,1,SIM,3,SEM FERIMENTOS,Masculino,SIM,NÃO,25.0,B,"VEICULOS MOTOR. COM ATE 8 PASSAGEIROS, PESO MA...",AUTOMOVEL,NÃO,NÃO

In [82]:
dfs_limpos['veiculos'].head(5)

,cod_boletim,seq_veic,cod_categ,descricao_categoria,cod_especie,descricao_especie,cod_situacao,desc_situacao,tipo_socorro,desc_tipo_socorro
0,2016026389227001,1,3,PARTICULAR,6,AUTOMOVEL,1,EM MOVIMENTO,0,NÃO INFORMADO
1,2016026413610001,1,3,PARTICULAR,6,AUTOMOVEL,1,EM MOVIMENTO,0,NÃO INFORMADO
2,2016026416184001,1,3,PARTICULAR,6,AUTOMOVEL,1,EM MOVIMENTO,0,NÃO INFORMADO
3,2016026419084001,1,3,PARTICULAR,6,AUTOMOVEL,1,EM MOVIMENTO,0,NÃO INFORMADO
4,2016026419620001,1,3,PARTICULAR,6,AUTOMOVEL,1,EM MOVIMENTO,0,NÃO INFORMADO

In [83]:
dfs_limpos['veiculos'].info()

<class 'pandas.DataFrame'>
RangeIndex: 129826 entries, 0 to 129825
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   cod_boletim          129826 non-null  str
 1   seq_veic             129826 non-null  int64
 2   cod_categ            129826 non-null  int64
 3   descricao_categoria  129826 non-null  str
 4   cod_especie          129826 non-null  int64
 5   descricao_especie    129826 non-null  str
 6   cod_situacao         129826 non-null  int64
 7   desc_situacao        129826 non-null  str
 8   tipo_socorro         129826 non-null  int64
 9   desc_tipo_socorro    129826 non-null  str
dtypes: int64(5), str(5)
memory usage: 19.5 MB

In [84]:
dfs_limpos['veiculos'].isnull().sum()

cod_boletim            0
seq_veic               0
cod_categ              0
descricao_categoria    0
cod_especie            0
descricao_especie      0
cod_situacao           0
desc_situacao          0
tipo_socorro           0
desc_tipo_socorro      0
dtype: int64

In [66]:
dfs_limpos['veiculos']['desc_situacao'] = dfs_limpos['veiculos']['desc_situacao'].fillna('NAO INFORMADO')

In [70]:
dfs_limpos['logradouros'].head(5)

,cod_boletim,nome_municipio,seq_logradouros,tipo_logradouro,nome_logradouro,tipo_bairro,descricao_tipo_bairro,num_imovel,bairro
0,2016018874465001,BELO HORIZONTE,2,RUA,SAO PAULO,B,BAIRRO,0,Centro
1,2016023140518001,BELO HORIZONTE,2,RUA,SAO PAULO,B,BAIRRO,0,Centro
2,2016017382500001,BELO HORIZONTE,2,RUA,SAO PAULO,B,BAIRRO,0,Centro
3,2016017506366001,BELO HORIZONTE,2,RUA,SAO PAULO,B,BAIRRO,0,Centro
4,2016017977743001,BELO HORIZONTE,2,RUA,SAO PAULO,B,BAIRRO,0,Centro

In [69]:
dfs_limpos['logradouros'] = dfs_limpos['logradouros'].rename(columns={'nº_imovel' : 'num_imovel'})

In [ ]:
import os
import pandas as pd
import numpy as np

folder_path = '../data/dados_tratados'
os.makedirs(folder_path, exist_ok=True)

for nome_tabela, df in dfs_limpos.items():
   
    temp_df = df.copy()

    
    if 'idade' in temp_df.columns and nome_tabela == 'envolvidos':
        
        mediana = int(temp_df[temp_df['idade'].between(1, 98)]['idade'].median())
        
        temp_df['idade'] = temp_df['idade'].apply(lambda x: mediana if x == 0 or x > 98 or pd.isna(x) else int(x))
        temp_df['idade'] = temp_df['idade'].astype(int)

    for col in temp_df.columns:
        
        temp_df[col] = pd.Series(temp_df[col].to_numpy(), name=col)

    cols_obj = temp_df.select_dtypes(include=['object', 'string']).columns
    for col in cols_obj:
        temp_df[col] = temp_df[col].astype(str)

    file_path = os.path.join(folder_path, f"{nome_tabela}.parquet")
    
    # Se o fastparquet continuar dando erro, vamos usar o pyarrow como motor
    try:
        temp_df.to_parquet(file_path, index=False, engine='pyarrow')
    except:
        temp_df.to_parquet(file_path, index=False, engine='fastparquet')
    
    print(f"✅ Sucesso total: {file_path}")

✅ Sucesso total: ../data/dados_tratados/boletins.parquet
✅ Sucesso total: ../data/dados_tratados/envolvidos.parquet
✅ Sucesso total: ../data/dados_tratados/veiculos.parquet
✅ Sucesso total: ../data/dados_tratados/logradouros.parquet
✅ Sucesso total: ../data/dados_tratados/coordenadas.parquet

In [89]:
# Lendo o arquivo que mais deu trabalho
df_teste = pd.read_parquet('../data/dados_tratados/envolvidos.parquet')

print("--- Check de Integridade ---")
print(f"Linhas carregadas: {len(df_teste)}")
print(f"Tipo da coluna idade: {df_teste['idade'].dtype}")
print(f"Idades únicas (top 5): \n{df_teste['idade'].value_counts().head()}")

# Mostra as primeiras linhas para ver se a hora está legível
display(df_teste[['cod_boletim', 'sexo', 'idade']].head())

--- Check de Integridade ---
Linhas carregadas: 154713
Tipo da coluna idade: int64
Idades únicas (top 5):
idade
34    15207
24     4744
22     4734
23     4621
25     4553
Name: count, dtype: int64

        cod_boletim       sexo  idade
0  2017004467915001  Masculino     25
1  2017029493511001  Masculino     25
2  2017027452746001  Masculino     25
3  2017030345024001  Masculino     25
4  2017030388086001  Masculino     25